version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GCS_BUCKET=${GCS_BUCKET}
      - PROJECT_ID=${PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials.json:ro
